test_print – FTorch
test_print Subroutine
MIT
12 statements
Source File
public subroutine test_print(test_name, message, test_pass)
Print the result of a test to the terminal
Arguments
Type Intent Optional Attributes Name
character(len=*), intent(in) :: test_name
Name of the test being run
character(len=*), intent(in) :: message
Message to print
logical, intent(in) :: test_pass
Result of the value comparison
Called by
Source Code
    subroutine test_print(test_name, message, test_pass)
      character(len=*), intent(in) :: test_name  !! Name of the test being run
      character(len=*), intent(in) :: message    !! Message to print
      logical, intent(in) :: test_pass           !! Result of the value comparison
      character(len=15) :: report
      if (test_pass) then
        report = char(27)//'[32m'//'PASSED'//char(27)//'[0m'
      else
        report = char(27)//'[31m'//'FAILED'//char(27)//'[0m'
      end if
      write(*, '(A, " :: [", A, "] ", A)') report, trim(test_name), trim(message)
    end subroutine test_print
Call graph
allclose_real32_1d calls test_print
allclose_real32_2d calls test_print
allclose_real32_3d calls test_print
allclose_real64_1d calls test_print
allclose_real64_2d calls test_print
allclose_real64_3d calls test_print
isclose_real32 calls test_print
isclose_real64 calls test_print
allclose calls allclose_real32_1d, allclose_real32_2d, allclose_real32_3d, allclose_real64_1d, allclose_real64_2d, allclose_real64_3d
isclose calls isclose_real32, isclose_real64
assert_allclose_real32_1d calls allclose_real32_1d
assert_allclose_real32_2d calls allclose_real32_2d
assert_allclose_real32_3d calls allclose_real32_3d
assert_allclose_real64_1d calls allclose_real64_1d
assert_allclose_real64_2d calls allclose_real64_2d
assert_allclose_real64_3d calls allclose_real64_3d
assert_isclose_real32 calls isclose_real32
assert_isclose_real64 calls isclose_real64
assert_allclose calls assert_allclose_real32_1d, assert_allclose_real32_2d, assert_allclose_real32_3d, assert_allclose_real64_1d, assert_allclose_real64_2d, assert_allclose_real64_3d
assert_isclose calls assert_isclose_real32, assert_isclose_real64