torch_tensor_get_device_type – FTorch
torch_tensor_get_device_type Function
MIT
18 statements
Source File
public function torch_tensor_get_device_type(self) result(device_type)
Uses
iso_c_binding
Returns the device type of a tensor.
Type Bound
torch_tensor
Arguments
Type Intent Optional Attributes Name
class(torch_tensor), intent(in) :: self
Tensor to get the device type of
Return Value integer(kind=c_int)
Device type of tensor
Called by
Source Code
  function torch_tensor_get_device_type(self) result(device_type)
    use, intrinsic :: iso_c_binding, only : c_int
    class(torch_tensor), intent(in) :: self  !! Tensor to get the device type of
    integer(c_int) :: device_type            !! Device type of tensor
    interface
      function torch_tensor_get_device_type_c(tensor_c) result(device_type_c) &
          bind(c, name = 'torch_tensor_get_device_type')
        use, intrinsic :: iso_c_binding, only : c_int, c_ptr
        implicit none
        type(c_ptr), value, intent(in) :: tensor_c
        integer(c_int) :: device_type_c
      end function torch_tensor_get_device_type_c
    end interface
    if (.not. c_associated(self%p)) then
      write(*,*) "Error :: tensor has not been constructed so its device type is unset"
      stop 1
    end if
    device_type = torch_tensor_get_device_type_c(self%p)
  end function torch_tensor_get_device_type
Call graph
torch_tensor_add calls torch_tensor_get_device_type
torch_tensor_assign calls torch_tensor_get_device_type
torch_tensor_divide calls torch_tensor_get_device_type
torch_tensor_multiply calls torch_tensor_get_device_type
torch_tensor_negative calls torch_tensor_get_device_type
torch_tensor_power_int16 calls torch_tensor_get_device_type
torch_tensor_power_int32 calls torch_tensor_get_device_type
torch_tensor_power_int64 calls torch_tensor_get_device_type
torch_tensor_power_int8 calls torch_tensor_get_device_type
torch_tensor_power_real32 calls torch_tensor_get_device_type
torch_tensor_power_real64 calls torch_tensor_get_device_type
torch_tensor_subtract calls torch_tensor_get_device_type
assignment (=) calls torch_tensor_assign
operator (+) calls torch_tensor_add
operator (ASTERISK) calls torch_tensor_multiply
operator (ASTERISKASTERISK) calls torch_tensor_power_int16, torch_tensor_power_int32, torch_tensor_power_int64, torch_tensor_power_int8, torch_tensor_power_real32, torch_tensor_power_real64
operator (SLASH) calls torch_tensor_divide