torch_tensor_multiply – FTorch
torch_tensor_multiply Function
MIT
14 statements
Source File
public function torch_tensor_multiply(tensor1, tensor2) result(output)
Uses
iso_c_binding
Overloads multiplication operator for two tensors.
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor1
First tensor to be multiplied
type(torch_tensor), intent(in) :: tensor2
Second tensor to be multiplied
Return Value type(torch_tensor)
Tensor to hold the product
Calls
Called by
Source Code
  function torch_tensor_multiply(tensor1, tensor2) result(output)
    use, intrinsic :: iso_c_binding, only : c_associated
    type(torch_tensor), intent(in) :: tensor1  !! First tensor to be multiplied
    type(torch_tensor), intent(in) :: tensor2  !! Second tensor to be multiplied
    type(torch_tensor) :: output               !! Tensor to hold the product
    if (tensor1%get_device_type() /= tensor2%get_device_type()) then
      write(*,*) "Error :: cannot multiply tensors with different device types"
      stop 1
    end if
    if (.not. c_associated(output%p)) then
      call torch_tensor_empty(output, tensor1%get_rank(), tensor1%get_shape(), &
                              tensor1%get_dtype(), tensor1%get_device_type(), &
                              device_index=tensor1%get_device_index(), &
                              requires_grad=tensor1%requires_grad())
    end if
    call torch_tensor_multiply_c(output%p, tensor1%p, tensor2%p)
  end function torch_tensor_multiply
Call graph
torch_tensor_multiply calls torch_tensor_multiply_c, torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_get_shape calls torch_tensor_get_rank
operator (ASTERISK) calls torch_tensor_multiply