torch_tensor_get_shape – FTorch
torch_tensor_get_shape Function
MIT
22 statements
Source File
public function torch_tensor_get_shape(self) result(sizes)
Uses
iso_c_binding
Determines the shape of a tensor.
Type Bound
torch_tensor
Arguments
Type Intent Optional Attributes Name
class(torch_tensor), intent(in) :: self
Tensor to get the shape of
Return Value integer(kind=c_int64_t), pointer, (:)
Pointer to tensor data
Calls
Called by
Source Code
  function torch_tensor_get_shape(self) result(sizes)
    use, intrinsic :: iso_c_binding, only : c_f_pointer, c_int, c_int64_t, c_ptr
    class(torch_tensor), intent(in) :: self         !! Tensor to get the shape of
    integer(kind=c_int64_t), pointer :: sizes(:)       !! Pointer to tensor data
    ! Local data
    integer(kind=int32) :: ndims(1)
    type(c_ptr) :: cptr
    interface
      function torch_tensor_get_sizes_c(tensor_c) result(sizes_c) &
          bind(c, name = 'torch_tensor_get_sizes')
        use, intrinsic :: iso_c_binding, only : c_int, c_long, c_ptr
        implicit none
        type(c_ptr), value, intent(in) :: tensor_c
        type(c_ptr) :: sizes_c
      end function torch_tensor_get_sizes_c
    end interface
    if (.not. c_associated(self%p)) then
      write(*,*) "Error :: tensor has not been constructed so its shape is unset"
      stop 1
    end if
    ndims(1) = self%get_rank()
    cptr = torch_tensor_get_sizes_c(self%p)
    call c_f_pointer(cptr, sizes, ndims)
  end function torch_tensor_get_shape
Call graph
torch_tensor_get_shape calls torch_tensor_get_rank
torch_tensor_add calls torch_tensor_get_shape
torch_tensor_assign calls torch_tensor_get_shape
torch_tensor_backward_without_external_gradient calls torch_tensor_get_shape
torch_tensor_divide calls torch_tensor_get_shape
torch_tensor_multiply calls torch_tensor_get_shape
torch_tensor_negative calls torch_tensor_get_shape
torch_tensor_power_int16 calls torch_tensor_get_shape
torch_tensor_power_int32 calls torch_tensor_get_shape
torch_tensor_power_int64 calls torch_tensor_get_shape
torch_tensor_power_int8 calls torch_tensor_get_shape
torch_tensor_power_real32 calls torch_tensor_get_shape
torch_tensor_power_real64 calls torch_tensor_get_shape
torch_tensor_subtract calls torch_tensor_get_shape
torch_tensor_to calls torch_tensor_get_shape
assignment (=) calls torch_tensor_assign
operator (+) calls torch_tensor_add
operator (ASTERISK) calls torch_tensor_multiply
operator (ASTERISKASTERISK) calls torch_tensor_power_int16, torch_tensor_power_int32, torch_tensor_power_int64, torch_tensor_power_int8, torch_tensor_power_real32, torch_tensor_power_real64
operator (SLASH) calls torch_tensor_divide
torch_tensor_backward calls torch_tensor_backward_without_external_gradient