torch_tensor_delete – FTorch
torch_tensor_delete Subroutine
MIT
15 statements
Source File
public subroutine torch_tensor_delete(tensor)
Uses
iso_c_binding
Deallocates a tensor.
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(inout) :: tensor
Tensor to deallocate
Called by
Source Code
  subroutine torch_tensor_delete(tensor)
    use, intrinsic :: iso_c_binding, only : c_associated, c_null_ptr
    type(torch_tensor), intent(inout) :: tensor  !! Tensor to deallocate
    interface
      subroutine torch_tensor_delete_c(tensor_c) &
          bind(c, name = 'torch_tensor_delete')
        use, intrinsic :: iso_c_binding, only : c_ptr
        implicit none
        type(c_ptr), value, intent(in) :: tensor_c
      end subroutine torch_tensor_delete_c
    end interface
    ! Call the destructor, if it hasn't already been called
    if (c_associated(tensor%p)) then
      call torch_tensor_delete_c(tensor%p)
      tensor%p = c_null_ptr
    end if
  end subroutine torch_tensor_delete
Call graph
torch_delete calls torch_tensor_delete, torch_tensor_array_delete
torch_tensor_array_delete calls torch_tensor_delete
torch_tensor_backward calls torch_tensor_delete