torch_tensor_get_dtype – FTorch
torch_tensor_get_dtype Function
MIT
18 statements
Source File
public function torch_tensor_get_dtype(self) result(dtype)
Uses
iso_c_binding
Returns the data type of a tensor.
Type Bound
torch_tensor
Arguments
Type Intent Optional Attributes Name
class(torch_tensor), intent(in) :: self
Tensor to get the data type of
Return Value integer(kind=c_int)
Data type of tensor
Called by
Source Code
  function torch_tensor_get_dtype(self) result(dtype)
    use, intrinsic :: iso_c_binding, only : c_int
    class(torch_tensor), intent(in) :: self  !! Tensor to get the data type of
    integer(c_int) :: dtype                  !! Data type of tensor
    interface
      function torch_tensor_get_dtype_c(tensor_c) result(dtype_c) &
          bind(c, name = 'torch_tensor_get_dtype')
        use, intrinsic :: iso_c_binding, only : c_int, c_ptr
        implicit none
        type(c_ptr), value, intent(in) :: tensor_c
        integer(c_int) :: dtype_c
      end function torch_tensor_get_dtype_c
    end interface
    if (.not. c_associated(self%p)) then
      write(*,*) "Error :: tensor has not been constructed so its data type is unset"
      stop 1
    end if
    dtype = torch_tensor_get_dtype_c(self%p)
  end function torch_tensor_get_dtype
Call graph
torch_tensor_add calls torch_tensor_get_dtype
torch_tensor_assign calls torch_tensor_get_dtype
torch_tensor_backward calls torch_tensor_get_dtype
torch_tensor_divide calls torch_tensor_get_dtype
torch_tensor_multiply calls torch_tensor_get_dtype
torch_tensor_negative calls torch_tensor_get_dtype
torch_tensor_power_int16 calls torch_tensor_get_dtype
torch_tensor_power_int32 calls torch_tensor_get_dtype
torch_tensor_power_int64 calls torch_tensor_get_dtype
torch_tensor_power_int8 calls torch_tensor_get_dtype
torch_tensor_power_real32 calls torch_tensor_get_dtype
torch_tensor_power_real64 calls torch_tensor_get_dtype
torch_tensor_subtract calls torch_tensor_get_dtype
assignment (=) calls torch_tensor_assign
operator (+) calls torch_tensor_add
operator (ASTERISK) calls torch_tensor_multiply
operator (ASTERISKASTERISK) calls torch_tensor_power_int16, torch_tensor_power_int32, torch_tensor_power_int64, torch_tensor_power_int8, torch_tensor_power_real32, torch_tensor_power_real64
operator (SLASH) calls torch_tensor_divide