torch_tensor_get_device_index – FTorch
torch_tensor_get_device_index Function
MIT
18 statements
Source File
public function torch_tensor_get_device_index(self) result(device_index)
Uses
iso_c_binding
Determines the device index of a tensor.
Type Bound
torch_tensor
Arguments
Type Intent Optional Attributes Name
class(torch_tensor), intent(in) :: self
Tensor to get the device index of
Return Value integer(kind=c_int)
Device index of tensor
Called by
Source Code
  function torch_tensor_get_device_index(self) result(device_index)
    use, intrinsic :: iso_c_binding, only : c_int
    class(torch_tensor), intent(in) :: self  !! Tensor to get the device index of
    integer(c_int) :: device_index           !! Device index of tensor
    interface
      function torch_tensor_get_device_index_c(tensor_c) result(device_index_c) &
          bind(c, name = 'torch_tensor_get_device_index')
        use, intrinsic :: iso_c_binding, only : c_int, c_ptr
        implicit none
        type(c_ptr), value, intent(in) :: tensor_c
        integer(c_int) :: device_index_c
      end function torch_tensor_get_device_index_c
    end interface
    if (.not. c_associated(self%p)) then
      write(*,*) "Error :: tensor has not been constructed so its device index is unset"
      stop 1
    end if
    device_index = torch_tensor_get_device_index_c(self%p)
  end function torch_tensor_get_device_index
Call graph
torch_tensor_add calls torch_tensor_get_device_index
torch_tensor_assign calls torch_tensor_get_device_index
torch_tensor_backward calls torch_tensor_get_device_index
torch_tensor_divide calls torch_tensor_get_device_index
torch_tensor_multiply calls torch_tensor_get_device_index
torch_tensor_negative calls torch_tensor_get_device_index
torch_tensor_power_int16 calls torch_tensor_get_device_index
torch_tensor_power_int32 calls torch_tensor_get_device_index
torch_tensor_power_int64 calls torch_tensor_get_device_index
torch_tensor_power_int8 calls torch_tensor_get_device_index
torch_tensor_power_real32 calls torch_tensor_get_device_index
torch_tensor_power_real64 calls torch_tensor_get_device_index
torch_tensor_subtract calls torch_tensor_get_device_index
assignment (=) calls torch_tensor_assign
operator (+) calls torch_tensor_add
operator (ASTERISK) calls torch_tensor_multiply
operator (ASTERISKASTERISK) calls torch_tensor_power_int16, torch_tensor_power_int32, torch_tensor_power_int64, torch_tensor_power_int8, torch_tensor_power_real32, torch_tensor_power_real64
operator (SLASH) calls torch_tensor_divide