torch_tensor_get_rank – FTorch
torch_tensor_get_rank Function
MIT
17 statements
Source File
public function torch_tensor_get_rank(self) result(rank)
Determines the rank of a tensor.
Type Bound
torch_tensor
Arguments
Type Intent Optional Attributes Name
class(torch_tensor), intent(in) :: self
Tensor to get the rank of
Return Value integer(kind=int32)
Rank of tensor
Called by
Source Code
  function torch_tensor_get_rank(self) result(rank)
    class(torch_tensor), intent(in) :: self  !! Tensor to get the rank of
    integer(kind=int32) :: rank              !! Rank of tensor
    interface
      function torch_tensor_get_rank_c(tensor_c) result(rank_c) &
          bind(c, name = 'torch_tensor_get_rank')
        use, intrinsic :: iso_c_binding, only : c_int, c_ptr
        implicit none
        type(c_ptr), value, intent(in) :: tensor_c
        integer(c_int) :: rank_c
      end function torch_tensor_get_rank_c
    end interface
    if (.not. c_associated(self%p)) then
      write(*,*) "Error :: tensor has not been constructed so its rank is unset"
      stop 1
    end if
    rank = torch_tensor_get_rank_c(self%p)
  end function torch_tensor_get_rank
Call graph
torch_tensor_add calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_assign calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_backward_without_external_gradient calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_divide calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_get_shape calls torch_tensor_get_rank
torch_tensor_get_stride calls torch_tensor_get_rank
torch_tensor_multiply calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_negative calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_power_int16 calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_power_int32 calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_power_int64 calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_power_int8 calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_power_real32 calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_power_real64 calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_subtract calls torch_tensor_get_rank, torch_tensor_get_shape
torch_tensor_to calls torch_tensor_get_rank, torch_tensor_get_shape
assignment (=) calls torch_tensor_assign
operator (+) calls torch_tensor_add
operator (ASTERISK) calls torch_tensor_multiply
operator (ASTERISKASTERISK) calls torch_tensor_power_int16, torch_tensor_power_int32, torch_tensor_power_int64, torch_tensor_power_int8, torch_tensor_power_real32, torch_tensor_power_real64
operator (SLASH) calls torch_tensor_divide
torch_tensor_backward calls torch_tensor_backward_without_external_gradient