torch_tensor_power_real32 – FTorch
torch_tensor_power_real32 Function
MIT
20 statements
Source File
public function torch_tensor_power_real32(tensor, power) result(output)
Uses
iso_c_binding
iso_fortran_env
Overloads exponentiation operator for a tensor and a scalar of type real32
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor
Tensor to take the power of
real(kind=real32), intent(in), target :: power
Floating point exponent
Return Value type(torch_tensor)
Tensor to hold the exponentiation
Calls
Called by
Source Code
  function torch_tensor_power_real32(tensor, power) result(output)
    use, intrinsic :: iso_c_binding, only : c_associated, c_loc
    use, intrinsic :: iso_fortran_env, only : real32
    type(torch_tensor), intent(in) :: tensor                      !! Tensor to take the power of
    real(kind=real32), target, intent(in) :: power  !! Floating point exponent
    type(torch_tensor) :: output                                  !! Tensor to hold the exponentiation
    interface
      subroutine torch_tensor_power_float_c(output_c, tensor_c, power_c) &
          bind(c, name = 'torch_tensor_power_float')
        use, intrinsic :: iso_c_binding, only : c_ptr
        implicit none
        type(c_ptr), value, intent(in) :: output_c
        type(c_ptr), value, intent(in) :: tensor_c
        type(c_ptr), value, intent(in) :: power_c
      end subroutine torch_tensor_power_float_c
    end interface
    if (.not. c_associated(output%p)) then
      call torch_tensor_empty(output, tensor%get_rank(), tensor%get_shape(), tensor%get_dtype(), &
                              tensor%get_device_type(), device_index=tensor%get_device_index(), &
                              requires_grad=tensor%requires_grad())
    end if
    call torch_tensor_power_float_c(output%p, tensor%p, c_loc(power))
  end function torch_tensor_power_real32
Call graph
torch_tensor_power_real32 calls torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_get_shape calls torch_tensor_get_rank
operator (ASTERISKASTERISK) calls torch_tensor_power_real32