torch_tensor_requires_grad – FTorch
torch_tensor_requires_grad Function
MIT
13 statements
Source File
public function torch_tensor_requires_grad(self) result(requires_grad)
Determines whether a tensor requires the autograd module.
Type Bound
torch_tensor
Arguments
Type Intent Optional Attributes Name
class(torch_tensor), intent(in) :: self
Tensor to query
Return Value logical
Whether the tensor requires autograd
Called by
Source Code
  function torch_tensor_requires_grad(self) result(requires_grad)
    class(torch_tensor), intent(in) :: self  !! Tensor to query
    logical :: requires_grad                 !! Whether the tensor requires autograd
    interface
      function torch_tensor_requires_grad_c(tensor_c) result(requires_grad_c) &
          bind(c, name = 'torch_tensor_requires_grad')
        use, intrinsic :: iso_c_binding, only : c_bool, c_ptr
        implicit none
        type(c_ptr), value, intent(in) :: tensor_c
        logical(c_bool) :: requires_grad_c
      end function torch_tensor_requires_grad_c
    end interface
    requires_grad = torch_tensor_requires_grad_c(self%p)
  end function torch_tensor_requires_grad
Call graph
torch_tensor_add calls torch_tensor_requires_grad
torch_tensor_assign calls torch_tensor_requires_grad
torch_tensor_divide calls torch_tensor_requires_grad
torch_tensor_multiply calls torch_tensor_requires_grad
torch_tensor_negative calls torch_tensor_requires_grad
torch_tensor_power_int16 calls torch_tensor_requires_grad
torch_tensor_power_int32 calls torch_tensor_requires_grad
torch_tensor_power_int64 calls torch_tensor_requires_grad
torch_tensor_power_int8 calls torch_tensor_requires_grad
torch_tensor_power_real32 calls torch_tensor_requires_grad
torch_tensor_power_real64 calls torch_tensor_requires_grad
torch_tensor_subtract calls torch_tensor_requires_grad
assignment (=) calls torch_tensor_assign
operator (+) calls torch_tensor_add
operator (ASTERISK) calls torch_tensor_multiply
operator (ASTERISKASTERISK) calls torch_tensor_power_int16, torch_tensor_power_int32, torch_tensor_power_int64, torch_tensor_power_int8, torch_tensor_power_real32, torch_tensor_power_real64
operator (SLASH) calls torch_tensor_divide