allclose – FTorch
allclose Interface
MIT
8 statements
Source File
public interface allclose
Calls
Module Procedures
public function allclose_real32_1d(got, expect, test_name, rtol, print_result) result(test_pass)
Determines whether two real32-valued 1D arrays coincide to a given relative tolerance
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:) :: got
The array of values to be tested
real(kind=real32), intent(in), dimension(:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real32), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the comparison pass?
public function allclose_real32_2d(got, expect, test_name, rtol, print_result) result(test_pass)
Determines whether two real32-valued 2D arrays coincide to a given relative tolerance
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:,:) :: got
The array of values to be tested
real(kind=real32), intent(in), dimension(:,:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real32), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the comparison pass?
public function allclose_real32_3d(got, expect, test_name, rtol, print_result) result(test_pass)
Determines whether two real32-valued 3D arrays coincide to a given relative tolerance
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:,:,:) :: got
The array of values to be tested
real(kind=real32), intent(in), dimension(:,:,:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real32), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the comparison pass?
public function allclose_real64_1d(got, expect, test_name, rtol, print_result) result(test_pass)
Determines whether two real64-valued 1D arrays coincide to a given relative tolerance
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:) :: got
The array of values to be tested
real(kind=real64), intent(in), dimension(:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real64), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the comparison pass?
public function allclose_real64_2d(got, expect, test_name, rtol, print_result) result(test_pass)
Determines whether two real64-valued 2D arrays coincide to a given relative tolerance
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:,:) :: got
The array of values to be tested
real(kind=real64), intent(in), dimension(:,:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real64), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the comparison pass?
public function allclose_real64_3d(got, expect, test_name, rtol, print_result) result(test_pass)
Determines whether two real64-valued 3D arrays coincide to a given relative tolerance
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:,:,:) :: got
The array of values to be tested
real(kind=real64), intent(in), dimension(:,:,:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real64), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the comparison pass?
Call graph
allclose calls allclose_real32_1d, allclose_real32_2d, allclose_real32_3d, allclose_real64_1d, allclose_real64_2d, allclose_real64_3d
allclose_real32_1d calls test_print
allclose_real32_2d calls test_print
allclose_real32_3d calls test_print
allclose_real64_1d calls test_print
allclose_real64_2d calls test_print
allclose_real64_3d calls test_print