assert_allclose – FTorch
assert_allclose Interface
MIT
8 statements
Source File
public interface assert_allclose
Calls
Module Procedures
public function assert_allclose_real32_1d(got, expect, test_name, rtol, print_result) result(test_pass)
Alias for allclose_real32_1d
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:) :: got
The array of values to be tested
real(kind=real32), intent(in), dimension(:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real32), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the assertion pass?
public function assert_allclose_real32_2d(got, expect, test_name, rtol, print_result) result(test_pass)
Alias for allclose_real32_2d
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:,:) :: got
The array of values to be tested
real(kind=real32), intent(in), dimension(:,:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real32), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the assertion pass?
public function assert_allclose_real32_3d(got, expect, test_name, rtol, print_result) result(test_pass)
Alias for allclose_real32_3d
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=real32), intent(in), dimension(:,:,:) :: got
The array of values to be tested
real(kind=real32), intent(in), dimension(:,:,:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real32), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the assertion pass?
public function assert_allclose_real64_1d(got, expect, test_name, rtol, print_result) result(test_pass)
Alias for allclose_real64_1d
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:) :: got
The array of values to be tested
real(kind=real64), intent(in), dimension(:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real64), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the assertion pass?
public function assert_allclose_real64_2d(got, expect, test_name, rtol, print_result) result(test_pass)
Alias for allclose_real64_2d
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:,:) :: got
The array of values to be tested
real(kind=real64), intent(in), dimension(:,:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real64), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the assertion pass?
public function assert_allclose_real64_3d(got, expect, test_name, rtol, print_result) result(test_pass)
Alias for allclose_real64_3d
Read more…
Arguments
Type Intent Optional Attributes Name
real(kind=real64), intent(in), dimension(:,:,:) :: got
The array of values to be tested
real(kind=real64), intent(in), dimension(:,:,:) :: expect
The array of expected values
character(len=*), intent(in) :: test_name
Name of the test being run
real(kind=real64), intent(in), optional :: rtol
Optional relative tolerance (defaults to 1e-5)
logical, intent(in), optional :: print_result
Optionally print test result to screen (defaults to .true.)
Return Value logical
Did the assertion pass?
Call graph
assert_allclose calls assert_allclose_real32_1d, assert_allclose_real32_2d, assert_allclose_real32_3d, assert_allclose_real64_1d, assert_allclose_real64_2d, assert_allclose_real64_3d
assert_allclose_real32_1d calls allclose_real32_1d
assert_allclose_real32_2d calls allclose_real32_2d
assert_allclose_real32_3d calls allclose_real32_3d
assert_allclose_real64_1d calls allclose_real64_1d
assert_allclose_real64_2d calls allclose_real64_2d
assert_allclose_real64_3d calls allclose_real64_3d
allclose_real32_1d calls test_print
allclose_real32_2d calls test_print
allclose_real32_3d calls test_print
allclose_real64_1d calls test_print
allclose_real64_2d calls test_print
allclose_real64_3d calls test_print