operator (*) – FTorch
operator (*) Interface
MIT
3 statements
Source File
public interface operator (*)
Calls
Module Procedures
public function torch_tensor_multiply(tensor1, tensor2) result(output)
Overloads multiplication operator for two tensors.
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor1
First tensor to be multiplied
type(torch_tensor), intent(in) :: tensor2
Second tensor to be multiplied
Return Value type(torch_tensor)
Tensor to hold the product
Call graph
operator (ASTERISK) calls torch_tensor_multiply
torch_tensor_multiply calls torch_tensor_multiply_c, torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_get_shape calls torch_tensor_get_rank