operator (/) – FTorch
operator (/) Interface
MIT
3 statements
Source File
public interface operator (/)
Calls
Module Procedures
public function torch_tensor_divide(tensor1, tensor2) result(output)
Overloads division operator for two tensors.
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor1
First tensor for the division
type(torch_tensor), intent(in) :: tensor2
Second tensor for the division
Return Value type(torch_tensor)
Tensor to hold the quotient
Call graph
operator (SLASH) calls torch_tensor_divide
torch_tensor_divide calls torch_tensor_divide_c, torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_get_shape calls torch_tensor_get_rank