operator (**) – FTorch
operator (**) Interface
MIT
8 statements
Source File
public interface operator (**)
Calls
Module Procedures
public function torch_tensor_power_int8(tensor, power) result(output)
Overloads exponentiation operator for a tensor and a scalar of type int8
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor
Tensor to take the power of
integer(kind=int8), intent(in), target :: power
Integer exponent
Return Value type(torch_tensor)
Tensor to hold the exponentiation
public function torch_tensor_power_int16(tensor, power) result(output)
Overloads exponentiation operator for a tensor and a scalar of type int16
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor
Tensor to take the power of
integer(kind=int16), intent(in), target :: power
Integer exponent
Return Value type(torch_tensor)
Tensor to hold the exponentiation
public function torch_tensor_power_int32(tensor, power) result(output)
Overloads exponentiation operator for a tensor and a scalar of type int32
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor
Tensor to take the power of
integer(kind=int32), intent(in), target :: power
Integer exponent
Return Value type(torch_tensor)
Tensor to hold the exponentiation
public function torch_tensor_power_int64(tensor, power) result(output)
Overloads exponentiation operator for a tensor and a scalar of type int64
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor
Tensor to take the power of
integer(kind=int64), intent(in), target :: power
Integer exponent
Return Value type(torch_tensor)
Tensor to hold the exponentiation
public function torch_tensor_power_real32(tensor, power) result(output)
Overloads exponentiation operator for a tensor and a scalar of type real32
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor
Tensor to take the power of
real(kind=real32), intent(in), target :: power
Floating point exponent
Return Value type(torch_tensor)
Tensor to hold the exponentiation
public function torch_tensor_power_real64(tensor, power) result(output)
Overloads exponentiation operator for a tensor and a scalar of type real64
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor
Tensor to take the power of
real(kind=real64), intent(in), target :: power
Floating point exponent
Return Value type(torch_tensor)
Tensor to hold the exponentiation
Call graph
operator (ASTERISKASTERISK) calls torch_tensor_power_int16, torch_tensor_power_int32, torch_tensor_power_int64, torch_tensor_power_int8, torch_tensor_power_real32, torch_tensor_power_real64
torch_tensor_power_int16 calls torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_power_int32 calls torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_power_int64 calls torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_power_int8 calls torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_power_real32 calls torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_power_real64 calls torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_get_shape calls torch_tensor_get_rank