operator (-) – FTorch
operator (-) Interface
MIT
4 statements
Source File
public interface operator (-)
Calls
Module Procedures
public function torch_tensor_negative(tensor) result(output)
Overloads negative operator for a single tensor.
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor
Tensor to take the negative of
Return Value type(torch_tensor)
Tensor to hold the negative values
public function torch_tensor_subtract(tensor1, tensor2) result(output)
Overloads subtraction operator for two tensors.
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(in) :: tensor1
First tensor for the subtraction
type(torch_tensor), intent(in) :: tensor2
Second tensor for the subtraction
Return Value type(torch_tensor)
Tensor to hold the difference
Call graph
torch_tensor_negative calls torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_subtract calls torch_tensor_empty, torch_tensor_get_device_index, torch_tensor_get_device_type, torch_tensor_get_dtype, torch_tensor_get_rank, torch_tensor_get_shape, torch_tensor_requires_grad
torch_tensor_get_shape calls torch_tensor_get_rank