torch_from_blob_c – FTorch
torch_from_blob_c Interface
MIT
15 statements
Source File
interface
Called by
public function torch_from_blob_c(data, ndims, tensor_shape, strides, dtype, device_type, device_index, requires_grad) result(tensor_p) bind(c, name = 'torch_from_blob')
Arguments
Type Intent Optional Attributes Name
type(c_ptr), intent(in), value :: data
integer(kind=c_int), intent(in), value :: ndims
integer(kind=c_int64_t), intent(in) :: tensor_shape(*)
integer(kind=c_int64_t), intent(in) :: strides(*)
integer(kind=c_int), intent(in), value :: dtype
integer(kind=c_int), intent(in), value :: device_type
integer(kind=c_int), intent(in), value :: device_index
logical(kind=c_bool), intent(in), value :: requires_grad
Return Value type(c_ptr)
Call graph
torch_tensor_from_blob calls torch_from_blob_c
torch_tensor_from_array_int16_1d calls torch_tensor_from_blob
torch_tensor_from_array_int16_2d calls torch_tensor_from_blob
torch_tensor_from_array_int16_3d calls torch_tensor_from_blob
torch_tensor_from_array_int16_4d calls torch_tensor_from_blob
torch_tensor_from_array_int16_5d calls torch_tensor_from_blob
torch_tensor_from_array_int32_1d calls torch_tensor_from_blob
torch_tensor_from_array_int32_2d calls torch_tensor_from_blob
torch_tensor_from_array_int32_3d calls torch_tensor_from_blob
torch_tensor_from_array_int32_4d calls torch_tensor_from_blob
torch_tensor_from_array_int32_5d calls torch_tensor_from_blob
torch_tensor_from_array_int64_1d calls torch_tensor_from_blob
torch_tensor_from_array_int64_2d calls torch_tensor_from_blob
torch_tensor_from_array_int64_3d calls torch_tensor_from_blob
torch_tensor_from_array_int64_4d calls torch_tensor_from_blob
torch_tensor_from_array_int64_5d calls torch_tensor_from_blob
torch_tensor_from_array_int8_1d calls torch_tensor_from_blob
torch_tensor_from_array_int8_2d calls torch_tensor_from_blob
torch_tensor_from_array_int8_3d calls torch_tensor_from_blob
torch_tensor_from_array_int8_4d calls torch_tensor_from_blob
torch_tensor_from_array_int8_5d calls torch_tensor_from_blob
torch_tensor_from_array_real32_1d calls torch_tensor_from_blob
torch_tensor_from_array_real32_2d calls torch_tensor_from_blob
torch_tensor_from_array_real32_3d calls torch_tensor_from_blob
torch_tensor_from_array_real32_4d calls torch_tensor_from_blob
torch_tensor_from_array_real32_5d calls torch_tensor_from_blob
torch_tensor_from_array_real64_1d calls torch_tensor_from_blob
torch_tensor_from_array_real64_2d calls torch_tensor_from_blob
torch_tensor_from_array_real64_3d calls torch_tensor_from_blob
torch_tensor_from_array_real64_4d calls torch_tensor_from_blob
torch_tensor_from_array_real64_5d calls torch_tensor_from_blob
torch_tensor_from_array calls torch_tensor_from_array_int16_1d, torch_tensor_from_array_int16_2d, torch_tensor_from_array_int16_3d, torch_tensor_from_array_int16_4d, torch_tensor_from_array_int16_5d, torch_tensor_from_array_int32_1d, torch_tensor_from_array_int32_2d, torch_tensor_from_array_int32_3d, torch_tensor_from_array_int32_4d, torch_tensor_from_array_int32_5d, torch_tensor_from_array_int64_1d, torch_tensor_from_array_int64_2d, torch_tensor_from_array_int64_3d, torch_tensor_from_array_int64_4d, torch_tensor_from_array_int64_5d, torch_tensor_from_array_int8_1d, torch_tensor_from_array_int8_2d, torch_tensor_from_array_int8_3d, torch_tensor_from_array_int8_4d, torch_tensor_from_array_int8_5d, torch_tensor_from_array_real32_1d, torch_tensor_from_array_real32_2d, torch_tensor_from_array_real32_3d, torch_tensor_from_array_real32_4d, torch_tensor_from_array_real32_5d, torch_tensor_from_array_real64_1d, torch_tensor_from_array_real64_2d, torch_tensor_from_array_real64_3d, torch_tensor_from_array_real64_4d, torch_tensor_from_array_real64_5d, torch_tensor_from_array_int16_1d_default_layout, torch_tensor_from_array_int16_2d_default_layout, torch_tensor_from_array_int16_3d_default_layout, torch_tensor_from_array_int16_4d_default_layout, torch_tensor_from_array_int16_5d_default_layout, torch_tensor_from_array_int32_1d_default_layout, torch_tensor_from_array_int32_2d_default_layout, torch_tensor_from_array_int32_3d_default_layout, torch_tensor_from_array_int32_4d_default_layout, torch_tensor_from_array_int32_5d_default_layout, torch_tensor_from_array_int64_1d_default_layout, torch_tensor_from_array_int64_2d_default_layout, torch_tensor_from_array_int64_3d_default_layout, torch_tensor_from_array_int64_4d_default_layout, torch_tensor_from_array_int64_5d_default_layout, torch_tensor_from_array_int8_1d_default_layout, torch_tensor_from_array_int8_2d_default_layout, torch_tensor_from_array_int8_3d_default_layout, torch_tensor_from_array_int8_4d_default_layout, torch_tensor_from_array_int8_5d_default_layout, torch_tensor_from_array_real32_1d_default_layout, torch_tensor_from_array_real32_2d_default_layout, torch_tensor_from_array_real32_3d_default_layout, torch_tensor_from_array_real32_4d_default_layout, torch_tensor_from_array_real32_5d_default_layout, torch_tensor_from_array_real64_1d_default_layout, torch_tensor_from_array_real64_2d_default_layout, torch_tensor_from_array_real64_3d_default_layout, torch_tensor_from_array_real64_4d_default_layout, torch_tensor_from_array_real64_5d_default_layout
torch_tensor_from_array_int16_1d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int16_2d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int16_3d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int16_4d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int16_5d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int32_1d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int32_2d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int32_3d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int32_4d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int32_5d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int64_1d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int64_2d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int64_3d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int64_4d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int64_5d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int8_1d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int8_2d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int8_3d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int8_4d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_int8_5d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_real32_1d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_real32_2d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_real32_3d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_real32_4d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_real32_5d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_real64_1d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_real64_2d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_real64_3d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_real64_4d_default_layout calls torch_tensor_from_array
torch_tensor_from_array_real64_5d_default_layout calls torch_tensor_from_array