torch_delete – FTorch
torch_delete Interface
MIT
5 statements
Source File
public interface torch_delete
Interface for deleting generic torch objects
Calls
Module Procedures
public subroutine torch_model_delete(model)
Deallocates a TorchScript model
Arguments
Type Intent Optional Attributes Name
type(torch_model), intent(in) :: model
Torch Model to deallocate
public subroutine torch_tensor_delete(tensor)
Deallocates a tensor.
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(inout) :: tensor
Tensor to deallocate
public subroutine torch_tensor_array_delete(tensor_array)
Deallocates an array of tensors.
Arguments
Type Intent Optional Attributes Name
type(torch_tensor), intent(inout), dimension(:) :: tensor_array
Array of tensors to deallocate
Call graph
torch_delete calls torch_model_delete, torch_tensor_array_delete, torch_tensor_delete
torch_tensor_array_delete calls torch_tensor_delete