# workflow to run the FTorch test suite

name: TestSuite

# Controls when the workflow will run
on:
  # Triggers the workflow on pushes to the "main" branch and any pull request events
  push:
    branches: [ "main"]
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Workflow run - one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "test-suite"
  test-suite:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install PyTorch
        run: |
          python -m pip install --upgrade pip
          pip install torch --index-url https://download.pytorch.org/whl/cpu

      - name: Build FTorch
        run: |
          export Torch_DIR=/usr/lib/python3/dist-packages
          export BUILD_DIR=$(pwd)/build
          mkdir ${BUILD_DIR}
          cd ${BUILD_DIR}
          cmake .. -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=${BUILD_DIR}
          cmake --build .
          cmake --install .

      - name: Integration tests
        run: |
          # TODO: More examples
          cd examples/1_SimpleNet
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release
          cmake --build .
          ctest
